name: FlyPlugin
version: '1.0'
main: dev.steph.flyplugin.Main
api-version: 1.20

commands:
  fly:
    description: Enables or disables flying mode
    permission: flyspeed.fly
  speed:
    description: Sets the flying or walking speed
    permission: flyspeed.speed
